# Generated by Django 4.2.23 on 2025-06-21 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('representante_legal', models.CharField(max_length=100)),
                ('dni_representante', models.CharField(max_length=20)),
                ('tipo_productos', models.CharField(max_length=100)),
                ('mercado_objetivo', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
