# Generated by Django 5.2.3 on 2025-06-20 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='business_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='ruc',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
