# Generated by Django 4.2.23 on 2025-06-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('product', '0001_initial'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='laboratory.laboratory'),
        ),
    ]
